on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0/15 * * * *"

name: Dashboard Mestrado

jobs:
  Dashboard-mestrado:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.DASH_MESTRADO }}
      RENV_PATHS_ROOT: ~/.local/share/renv
         
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
            
      - name: Install Devtolls
        run: |
           sudo apt-get update
           sudo apt-get install libcurl4-openssl-dev
           sudo apt-get install libssl-dev
           sudo apt-get install libgit2-dev
           sudo apt install r-cran-devtools

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::snapshot()
          renv::restore()
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown"))'
          Rscript -e 'install.packages(c("flexdashboard"))'
          Rscript -e 'install.packages("tidyverse")
          Rscript -e 'install.packages("plotly")
          Rscript -e 'install.packages("sf")
          Rscript -e 'install.packages("OpenStreetMap")
          Rscript -e 'install.packages("viridis")
          Rscript -e 'install.packages("metR")
          Rscript -e 'install.packages("readxl")
          Rscript -e 'install.packages("RColorBrewer")
          Rscript -e 'install.packages("chron")

      - name: Render R Markdown
        run: |
          Rscript -e 'rmarkdown::render("test_flexdashboard.Rmd", output_file = "index.html")'

      - name: Commit and push changes
        run: |
          git config --global user.name "GilbertQueiroz"
          git config --global user.email "gilbert_queiroz@yahoo.com.br"
          git add index.html
          git commit -m 'test_flexdashboard.Rmd to index.html' || echo "No changes to commit"
          git push
